# Generated by Django 3.1.4 on 2020-12-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
